# Generated by Django 6.0.2 on 2026-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_events',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='events.event'),
        ),
    ]
